spring:
  mvc:
    view:
      prefix: /		#前缀
      suffix: .jsp	#后缀
  http:
    encoding: #编码	  #字符集	#强制使用
      charset: UTF-8
      force: true
  datasource: #数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pos
    username: root
    password: 123456
  servlet:
    multipart: #最大文件大小  	#最大请求大小
      max-file-size: 1024MB
      max-request-size: 1024MB
mybatis: #mapper文件位置	#类型-别名-包
  mapper-locations: classpath:com/jiali/mapper/*.xml
  type-aliases-package: com.jiali.entity

server:
  servlet:
    context-path: /springboot
  port: 8989

